name: nexquub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  signals: ^6.0.2
  url_launcher: ^6.3.1
  sign_in_with_apple: ^7.0.1
  shared_preferences: ^2.5.3
  share_plus: ^11.0.0
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.4.0
  lottie: ^3.2.0
  keyboard_actions: ^4.2.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  google_sign_in: ^6.3.0
  go_router: ^15.1.1
  get_it: ^8.0.3
  flutter_svg: ^2.1.0
  flutter_secure_storage: ^4.2.1
  flutter_screenutil: ^5.9.3
  firebase_messaging: ^15.2.5
  firebase_crashlytics: ^4.3.5
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  extended_image: ^9.1.0
  dio: ^5.8.0+1
  flutter_animate: ^4.5.2
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  flutter_pdf_text: ^0.9.0
  docx_to_text: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.9

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/animation/

    